course/urls.py
from django.contrib import admin
from django.urls import path, include
from course.views import *
from course.cbvs import ScheduleDeleteView, ScoreUpdateView, RateUpdateView, StudentCourseDetailView
from . import views


urlpatterns = [
    path('', to_home, name="course"),
    path('<slug:kind>/', home, name="course"),
    path('teacher/create_course', create_course, name="create_course"),
    path('teacher/view_detail/<int:course_id>', view_detail, name="view_detail"),
    path('teacher/create_schedule/<int:course_id>', create_schedule, name="create_schedule"),
    path('teacher/delete_schedule/<int:schedule_id>', delete_schedule, name="delete_schedule"),
    path('teacher/score/<int:pk>', ScoreUpdateView.as_view(), name="score"),
    path('teacher/handle_course/<int:course_id>/<int:handle_kind>', handle_course, name="handle_course"),

    path('student/view/<slug:view_kind>', view_course, name="view_course"),
    path('student/operate/<int:course_id>/<slug:operate_kind>', operate_course, name="operate_course"),

    path('student/evaluate/<int:pk>', RateUpdateView.as_view(), name="evaluate"),
    path('student/view_detail/<int:pk>', StudentCourseDetailView.as_view(), name="sview_detail"),
    #添加PDF视图路由
    path('teacher/pdf/', HelloPDFView.as_view(), name='pdf'),
    #csv视图路由
    path('teacher/csv/', views.cvs),
]

scss/urls.py
# usr/bin/env python3
# -*- coding:utf-8- -*-
"""scss URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from user.views import login, home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include("user.urls")),
    path('course/', include("course.urls")),
    path('captcha/', include('captcha.urls')),
    #添加验证码url
    path('', home)
]

course/models.py
from django.db import models
import datetime
from user.models import Student, Teacher
from constants import COURSE_STATUS, COURSE_OPERATION


def current_year():
    # refer: https://stackoverflow.com/questions/49051017/year-field-in-django/49051348
    return datetime.date.today().year


class Course(models.Model):
    credits = [
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    ]
    semesters = [
        ("Autumn", "上"),
        ("Spring", "下")
    ]
    name = models.CharField(max_length=50, verbose_name="课程名")
    introduction = models.CharField(max_length=250, verbose_name="介绍")
    credit = models.IntegerField(verbose_name="学分")
    max_number = models.IntegerField(verbose_name="课程最大人数")

    year = models.IntegerField(verbose_name="年份", default=current_year)
    semester = models.CharField(max_length=20, verbose_name="学期", choices=semesters)

    # 未开始选课， 1
    # 开始选课，未结束选课 2
    # 结束选课， 3
    # 结课 4
    # 已打完分 5
    status = models.IntegerField(verbose_name="课程状态", default=1)

    teacher = models.ForeignKey(Teacher, verbose_name="课程教师", on_delete=models.CASCADE)

    def get_status_text(self):
        return COURSE_STATUS[self.status]

    def get_op_text(self):
        return COURSE_OPERATION[self.status]

    def get_current_count(self):
        courses = StudentCourse.objects.filter(course=self, with_draw=False)
        return len(courses)

    def get_schedules(self):
        schedules = Schedule.objects.filter(course=self)
        return schedules

    def __str__(self):
        return "%s (%s)" % (self.name, self.teacher.name)


def weekday_choices():
    weekday_str = ['周一', '周二', '周三', '周四', '周五', '周六', '周日']
    return [(i+1, weekday_str[i]) for i in range(7)]


class Schedule(models.Model):
    weekday = models.IntegerField(choices=weekday_choices(), verbose_name="日期")
    start_time = models.TimeField(verbose_name="上课时间")
    end_time = models.TimeField(verbose_name="下课时间")
    location = models.CharField(max_length=100, verbose_name="上课地点")
    remarks = models.CharField(max_length=100, verbose_name="备注", null=True, blank = True)

    start_week = models.IntegerField(verbose_name="第几周开始")
    end_week = models.IntegerField(verbose_name="第几周结束")

    intervals = [
        (1, "无间隔"),
        (2, "每隔一周上一次")
    ]
    week_interval = models.IntegerField(verbose_name="周间隔", choices=intervals, default=1)

    course = models.ForeignKey(Course, verbose_name="课程名", on_delete=models.CASCADE)

    def __str__(self):
        s = "第%s周-第%s周 " % (self.start_week, self.end_week)
        if self.week_interval == 2:
            s += "隔一周 "
        s += "%s %s-%s " % (self.get_weekday_display(), self.start_time.strftime("%H:%M"),
                            self.end_time.strftime("%H:%M"))
        s += "在%s" % self.location
        if self.remarks:
            s += " %s" % self.remarks
        return s


class StudentCourse(models.Model):
    create_time = models.DateTimeField(auto_now=True)
    with_draw = models.BooleanField(default=False)
    with_draw_time = models.DateTimeField(default=None, null=True)

    scores = models.IntegerField(verbose_name="成绩", null=True)
    comments = models.CharField(max_length=250, verbose_name="老师评价", null=True)

    rates = [
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    ]

    rating = models.IntegerField(verbose_name="学生评分", choices=rates, null=True, help_text="5分为最满意，最低分是1分")
    assessment = models.CharField(max_length=250, verbose_name="学生评价", null=True)

    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

course/forms.py
# usr/bin/env python
# -*- coding:utf-8- -*-
from django import forms
from .models import Course, Schedule, StudentCourse


class CourseForm(forms.ModelForm):

    class Meta:
        model = Course
        exclude = ['status', 'teacher']


class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        exclude = ["course"]


class ScoreForm(forms.ModelForm):
    class Meta:
        model = StudentCourse
        fields = ["student", "course", "scores", "comments"]

    student = forms.CharField(label="学生", disabled=True)
    # course = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    course = forms.CharField(label="课程", disabled=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.initial['student'] = self.instance.student
        self.initial['course'] = self.instance.course

    def clean_student(self):
        return self.initial['student']

    def clean_course(self):
        return self.initial['course']


class RateForm(forms.ModelForm):
    class Meta:
        model = StudentCourse
        fields = ["course", "scores", "comments", "rating", "assessment"]

    course = forms.CharField(label="课程", disabled=True)
    scores = forms.IntegerField(label="成绩", disabled=True)
    comments = forms.CharField(label="老师评价", disabled=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.initial['course'] = self.instance.course
        self.initial['scores'] = self.instance.scores
        self.initial['comments'] = self.instance.comments

    def clean_course(self):
        return self.initial['course']

    def clean_scores(self):
        return self.initial['scores']

    def clean_comments(self):
        return self.initial['comments']

course/views.py
#coding=UTF-8
from django.http.response import HttpResponse
from django.shortcuts import render, reverse, redirect
from django.db.models import Q
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from xhtml2pdf.default import DEFAULT_FONT

import csv
import codecs
from django.http import HttpResponse

from constants import INVALID_KIND, INVALID_REQUEST_METHOD, ILLEGAL_KIND
from course.forms import CourseForm, ScheduleForm
from course.models import Course, StudentCourse, Schedule
from user.util import get_user

from django.utils import timezone

from django.conf import settings
from easy_pdf.views import PDFTemplateView

def to_home(request):
    kind = request.session.get('kind', '')
    return redirect(reverse("course", kwargs={"kind": kind}))


def home(request, kind):
    if kind == "teacher":
        return teacher_home(request)
    elif kind == "student":
        return student_home(request)
    return HttpResponse(INVALID_KIND)


def teacher_home(request):
    user = get_user(request, "teacher")
    if not user:
        return redirect(reverse("login", kwargs={"kind": "teacher"}))

    info = {
        "name": user.name,
        "kind": "teacher",
    }

    is_search = False
    search_key = ""
    if request.method == "POST":
        search_key = request.POST.get("search")
        if search_key:
            is_search = True

    context = {"info": info}
    q = Q(teacher=user)
    if is_search:
        q = q & Q(name__icontains=search_key)
        context["search_key"] = search_key

    context["course_list"] = Course.objects.filter(q).order_by('status')

    return render(request, 'course/teacher/home.html', context)


def student_home(request):
    return redirect(reverse("view_course", kwargs={"view_kind": "current"}))


def create_course(request):
    user = get_user(request, "teacher")
    if not user:
        return redirect(reverse("login", kwargs={"kind": "teacher"}))

    info = {
        "name": user.name,
        "kind": "teacher",
    }

    if request.method == 'POST':
        form = CourseForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.status = 1
            obj.teacher = user

            obj.save()
            return redirect(reverse("course", kwargs={"kind": "teacher"}))
    elif request.method == 'GET':
        form = CourseForm()
    else:
        return HttpResponse(INVALID_REQUEST_METHOD)

    return render(request, 'course/teacher/create_course.html', {'info': info, 'form': form})


def create_schedule(request, course_id):
    user = get_user(request, "teacher")
    if not user:
        return redirect(reverse("login", kwargs={"kind": "teacher"}))

    info = {
        "name": user.name,
        "kind": "teacher",
    }

    course = Course.objects.get(pk=course_id)

    if request.method == 'POST':
        form = ScheduleForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.course = course
            obj.save()

            return redirect(reverse("view_detail", kwargs={"course_id": course_id}))
    elif request.method == 'GET':
        form = ScheduleForm()
    else:
        return HttpResponse(INVALID_REQUEST_METHOD)

    return render(request, 'course/teacher/create_schedule.html', {'info': info, 'form': form, "course": course})


def delete_schedule(request, schedule_id):
    user = get_user(request, "teacher")
    if not user:
        return redirect(reverse("login", kwargs={"kind": "teacher"}))

    schedule = Schedule.objects.get(pk=schedule_id)

    course_id = request.GET.get("course_id") or schedule.course.id

    schedule.delete()

    return redirect(reverse("view_detail", kwargs={"course_id": course_id}))


def handle_course(request, course_id, handle_kind):
    """
    :param request:
    :param course_id:
    :param handle_kind:
            1: "开始选课",
            2: "结束选课",
            3: "结课",
            4: "给分完成"
    :return:
    """
    user = get_user(request, "teacher")
    if not user:
        return redirect(reverse("login", kwargs={"kind": "teacher"}))

    info = {
        "name": user.name,
        "kind": "teacher",
    }

    course = Course.objects.get(pk=course_id)
    if course.status == handle_kind and course.status < 5:
        if course.status == 4:
            scs = StudentCourse.objects.filter(course=course)
            all_given = True
            res = ""
            for sc in scs:
                if sc.scores is None:
                    all_given = False
                    res += "<div>%s 未打分</div>" % sc.student

            if all_given:
                course.status += 1
                course.save()
                return redirect(reverse("view_detail", kwargs={"course_id": course.id}))
            else:
                return HttpResponse(res)
        else:
            course.status += 1
            course.save()

    course_list = Course.objects.filter(teacher=user)
    return render(request, 'course/teacher/home.html', {'info': info, 'course_list': course_list})


def view_detail(request, course_id):
    user = get_user(request, "teacher")
    if not user:
        return redirect(reverse("login", kwargs={"kind": "teacher"}))

    info = {
        "name": user.name,
        "kind": "teacher",
    }

    course = Course.objects.get(pk=course_id)
    c_stu_list = StudentCourse.objects.filter(course=course)
    sche_list = Schedule.objects.filter(course=course)

    context = {
        "info": info,
        "course": course,
        "course_students": c_stu_list,
        "schedules": sche_list
    }

    if course.status == 5:
        sorted_cs_list = sorted(c_stu_list, key=lambda cs: cs.scores)
        context["sorted_course_students"] = sorted_cs_list

    return render(request, "course/teacher/course.html", context)


def view_course(request, view_kind):
    """
    :param view_kind:
        current: 查看当前课程
        is_end: 查看结课课程
        select: 选课
        withdraw: 撤课
    """
    user = get_user(request, "student")
    if not user:
        return redirect(reverse("login", kwargs={"kind": "student"}))

    is_search = False
    search_key = ""
    if request.method == "POST":
        search_key = request.POST.get("search")
        if search_key:
            is_search = True

    info = {
        "name": user.name,
        "kind": "student",
    }

    course_list = []

    if view_kind in ["select", "current", "withdraw", "is_end"]:
        if view_kind == "select":
            q = Q(status=2)
            if is_search:
                q = q & (Q(name__icontains=search_key) | Q(teacher__name__icontains=search_key))

            course_list = Course.objects.filter(q)

            my_course = StudentCourse.objects.filter(Q(student=user) & Q(with_draw=False))
            my_cids = [c.course.id for c in my_course]
            course_list = [c for c in course_list if c.id not in my_cids]
        else:
            q = Q(student=user) & Q(with_draw=False)
            if is_search:
                q = q & (Q(course__name__icontains=search_key) | Q(course__teacher__name__icontains=search_key))
            my_course = StudentCourse.objects.filter(q)
            if view_kind == "current":
                course_list = [c.course for c in my_course if c.course.status < 4]
            elif view_kind == "withdraw":
                course_list = [c.course for c in my_course if c.course.status == 2]
            elif view_kind == "is_end":
                course_list = [c for c in my_course if c.course.status >= 4]

    else:
        return HttpResponse(INVALID_REQUEST_METHOD)

    context = {
        'info': info,
        'view_kind': view_kind,
        'course_list': course_list
    }
    if is_search:
        context["search_key"] = search_key

    return render(request, 'course/student/home.html', context)


def operate_course(request, operate_kind, course_id):
    """
    :param operate_kind:
        current: 查看当前课程
        is_end: 查看结课课程
        select: 选课
        withdraw: 撤课
    """
    user = get_user(request, "student")
    if not user:
        return redirect(reverse("login", kwargs={"kind": "student"}))

    if operate_kind not in ["select", "withdraw"]:
        return HttpResponse(ILLEGAL_KIND)
    elif operate_kind == "select":
        course = Course.objects.filter(pk=course_id).get()
        new_course = StudentCourse(student=user, course=course)
        new_course.save()
    elif operate_kind == "withdraw":
        q = Q(course__id=course_id) & Q(student=user) & Q(with_draw=False)
        course = StudentCourse.objects.filter(q).get()
        course.with_draw = True
        course.with_draw_time = timezone.now()
        course.save()

    return redirect(reverse("view_course", kwargs={"view_kind": operate_kind}))

'''
添加PDF视图
'''
class HelloPDFView(PDFTemplateView):
    template_name = 'course/pdf.html'  # html模板
    download_filename = 'hello.pdf'  # 下载pdf时的文件名

    def get_context_data(self, **kwargs):
        data = self.request.GET  # 可以获取请求参数

        return super(HelloPDFView, self).get_context_data(
            pagesize='A4',
            title='Hi there!',  # 转成pdf后文件上方的标题
            other='other',  # 也可以按需求增加自己需要的值，然后通过django的模板语言渲染到页面上
            **kwargs
        )

#csv视图
def cvs(request):
    response = HttpResponse(content_type='text/csv')
    response.write(codecs.BOM_UTF8) #格式
    # attachment 代表这个csv文件作为一个附件的形式下载
    # filename='abc.csv' 指定下载的文件名字
    response['Content-Disposition'] = 'attachment;filename="table.csv"'
    writer = csv.writer(response)
    writer.writerow(['星期一','星期二','星期三', '星期四','星期五','星期六','星期日'])
    writer.writerow(['云计算','Django',' ',''])    # 在这里并不会指定文件名字。
    writer.writerow(['', '大数据', ' ', 'Linux'])
    writer.writerow(['', '', '写作之道', ''])
    return response

templates/course/student/course.html
{% extends "course/nav.html" %}
{% block title %}课程详情{% endblock %}
{% block content %}
    {% load static %}
    <link href="{% static 'css/details.css' %}" rel="stylesheet">
    <h3>课程详情</h3>
    <ul class="course-details">
        <li class="course-detail"><span class="detail-name">课程编号</span> {{ object.course.id }}</li>
        <li class="course-detail"><span class="detail-name">课程名</span> {{ object.course.name }}</li>
        <li class="course-detail"><span class="detail-name">学分</span> {{ object.course.credit }}</li>
        <li class="course-detail"><span class="detail-name">课程人数/最大人数</span> {{ object.course.get_current_count }}/{{ object.course.max_number }}</li>
        <li class="course-detail"><span class="detail-name">年份</span> {{ object.course.year }}</li>
        <li class="course-detail"><span class="detail-name">学期</span> {{ object.course.get_semester_display }}</li>

        <li class="course-detail"><span class="detail-name">教师</span> {{ object.course.teacher.name }}</li>
        <li class="course-detail"><span class="detail-name">上课时间</span>
            <span class="course-schedules">
            {% for schedule in object.course.get_schedules %}
                <div class="course-schedule">{{ schedule }}</div>
                <div class="course-schedule">{{ schedule }}</div>
            {% endfor %}
            </span>
        </li>
        <li class="course-detail"><span class="detail-name">得分</span>
            {% if object.scores != None %}{{ object.scores }}{% else %} - {% endif %}
        </li>
        <li class="course-detail"><span class="detail-name">评语</span>
            {% if object.comments != None %}{{ object.comments }}{% else %} - {% endif %}
        </li>
        <li class="course-detail"><span class="detail-name">学生评分</span>
            {% if object.rating != None %}{{ object.rating }}{% else %} - {% endif %}
        </li>
        <li class="course-detail"><span class="detail-name">学生评价</span>
            {% if object.assessment != None %}{{ object.assessment }}{% else %} - {% endif %}
        </li>

    </ul>
    <input type="button" value="返回" onclick='location.href="{% url 'view_course' 'is_end'%}"' />
{% endblock %}

templates/course/student/home.html
{% extends "course/nav.html" %}
{% block title %}HomePage{% endblock %}
{% block content %}
    {% load static %}
    <link href="{% static 'css/list.css' %}" rel="stylesheet">
    <div class="main-container">
        <div class="main-bar">
            <form class="search-form" method="post">
                {% csrf_token %}
                <input class="input" id="search-key" type="text" name="search" {% if search_key != None %}value="{{ search_key }}" {% endif %}/>
                <input class="button" type="submit" value="搜索课程" />
            </form>

            {% if view_kind != "select"%}
                <input class="button right-button" type="button" value="选课"  onclick='window.open("{% url 'view_course' 'select' %}")' />
            {% endif %}
            {% if view_kind != "withdraw"%}
                <input class="button right-button" type="button" value="撤课"  onclick='window.open("{% url 'view_course' 'withdraw' %}")' />
            {% endif %}
            {% if view_kind != "is_end"%}
                <input class="button right-button" type="button" value="查看结课课程"  onclick='window.open("{% url 'view_course' 'is_end' %}")' />
            {% endif %}
            {% if view_kind != "current"%}
                <input class="button right-button" type="button" value="查看当前课程"  onclick='window.open("{% url 'view_course' 'current' %}")' />
            {% endif %}
        </div>
        <h3>{% if view_kind == "select"%}
                选课
            {% elif view_kind == "withdraw"%}
                撤课
            {% elif  view_kind == "is_end"%}
                查看结课课程
            {% elif view_kind == "current"%}
                查看当前课程
            {% endif %}</h3>
        <table class="item-list course-list">
            <thead>
                <tr>
                    <th class="course-no">课程编号</th>
                    <th class="course-name">名称</th>
                    <th class="course-credit">学分</th>
                    {% if view_kind == "is_end" %}
                        <th class="course-year-semester">年份学期</th>
                    {% else %}
                        <th class="course-number">当前人数/<br>最大人数</th>
                        <th class="course-year">年份</th>
                        <th class="course-semester">学期</th>
                    {% endif %}
                    <th class="course-teacher">教师</th>
                    {% if view_kind == "is_end" %}
                        <th class="course-scores">得分</th>
                        <th class="course-comments">评语</th>
                        <th class="course-rating">学生评分</th>
                        <th class="course-assessment">学生评价</th>
                        <th class="course-operation student-course">操作</th>
                    {% else %}
                        <th class="course-schedule">上课时间</th>
                        <th class="course-operation student-course">操作</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
            {% if view_kind == "is_end" %}
                {# end course show student course #}
                {% for sc in course_list %}
                <tr id="course-id-{{ sc.course.id }}">
                    <td class="course-no">{{ sc.course.id }}</td>
                    <td class="course-name">{{ sc.course.name }}</td>
                    <td class="course-credit">{{ sc.course.credit }}</td>
                    <td class="course-year-semester">{{ sc.course.year }} {{ sc.course.get_semester_display }}</td>
                    <td class="course-teacher">{{ sc.course.teacher.name }}</td>
                    <td class="course-scores">{{ sc.scores }}</td>
                    <td class="course-comments">{{ sc.comments }}</td>
                    {% if sc.rating == None %}
                        <td class="course-rating">-</td>
                        <td class="course-assessment">-</td>
                        <td class="course-operation student-course">
                        <input class="button" type="button" value="查看详情" onclick='location.href="{% url 'sview_detail' sc.id%}"' />
                        <input class="button" type="button" value="评教"
                               onclick='window.open("{% url 'evaluate' sc.id %}")' />
                        </td>
                    {% else %}
                        <td class="course-rating">{{ sc.rating }}</td>
                        <td class="course-assessment">{{ sc.assessment }}</td>
                        <td class="course-operation student-course">
                        <input class="button" type="button" value="查看详情" onclick='location.href="{% url 'sview_detail' sc.id%}"' />
                        </td>
                    {% endif %}
                </tr>
                {% endfor %}
            {% else %}
                {% for course in course_list %}
                <tr id="course-id-{{ course.id }}">
                    <td class="course-no">{{ course.id }}</td>
                    <td class="course-name">{{ course.name }}</td>
                    <td class="course-credit">{{ course.credit }}</td>
                    <td class="course-number">{{ course.get_current_count }}/{{ course.max_number }}</td>
                    <td class="course-year">{{ course.year }}</td>
                    <td class="course-semester">{{ course.get_semester_display }}</td>
                    <td class="course-teacher">{{ course.teacher.name }}</td>
                    <td class="course-schedule">
                        {% for schedule in course.get_schedules %}
                            <div>{{ schedule }}</div>
                        {% endfor %}
                    </td>
                        <td class="course-operation student-course">
                        {% if view_kind == "select"%}
                            <input class="button" type="button" value="选课"
                                   onclick='window.open("{% url 'operate_course' course.id 'select' %}")' />
                        {% endif %}
                        {% if view_kind == "withdraw"%}
                            <input class="button" type="button" value="撤课"
                                   onclick='window.open("{% url 'operate_course' course.id 'withdraw' %}")' />
                        {% endif %}
                        {% if view_kind == "current"%}
                            -
                        {% endif %}
                        </td>
                </tr>
                {% endfor %}
            {% endif %}
            </tbody>

        </table>
    </div>
{% endblock %}

templates/course/student/rating.html
{% extends "course/nav.html" %}
{% block title %}评教{% endblock %}
{% block content %}
    {% load static %}
    <link href="{% static 'css/form.css' %}" rel="stylesheet">
    <h3>评教</h3>
    <div class="form create-update-from">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <div class="submit-button">
                <input type="submit" value="确定"/>
                <input type="button" value="返回" onclick='location.href="{{ return_url }}"' />
            </div>
        </form>
    </div>
{% endblock %}